### ISSUE TITLE
Does not work with typed array data columns

### ISSUE THREAD

**Issue by etpinard** [dy/regl-splom#7]
Consider:

```js
const regl = require('regl')({ extensions: 'oes_element_index_uint' })
const createMatrix = require('./')

let splom = createMatrix(regl)

splom.update({
  data: [
    new Float32Array([1, 2, 3]),
    new Float32Array([4, 6, 8]),
    new Float32Array([1, 5, 9])
  ],
  ranges: [
    [0, 10],
    [0, 10],
    [0, 10]
  ],
  domain: [
    [0, 0, 0.3, 0.3],
    [0.35, 0.35, 0.65, 0.65],
    [0.7, 0.7, 1, 1] 
  ],
  color: ['red', 'green', 'blue'],
  size: [20, 10, 30]
})

splom.draw()
```

this gives:

![image](https://user-images.githubusercontent.com/6675409/39480368-fcf2e680-4d35-11e8-87bb-c261428f9e9c.png)

and a blank screen.

---

Is this a known limitation of this implementation? That is, should we try to convert typed array to plain arrays in plotly.js? Or would there be an easy way to make regl-splom accept typed arrays?

**Comment by dy** [comment]
Should be fixed in 1.0.1.

**Comment by etpinard** [comment]
Thanks @dy ! Sploms are now working with `Float32Array`, but they are still broken with `Int32Array` (as in https://github.com/plotly/plotly.js/issues/2585) and possibly other types.

For example,

```js
const regl = require('regl')({ extensions: 'oes_element_index_uint' })
const createMatrix = require('./')

let splom = createMatrix(regl)

splom.update({
  data: [
    new Int32Array([1, 2, 3]),
    new Int32Array([4, 6, 8]),
    new Int32Array([1, 5, 9])
  ],
  ranges: [
    [0, 10],
    [0, 10],
    [0, 10]
  ],
  domain: [
    [0, 0, 0.3, 0.3],
    [0.35, 0.35, 0.65, 0.65],
    [0.7, 0.7, 1, 1] 
  ],
  color: ['red', 'green', 'blue'],
  size: [20, 10, 30]
})

splom.draw()
```

gives

![image](https://user-images.githubusercontent.com/6675409/39492037-3f039e40-4d5c-11e8-9a12-c4d7ea0178fb.png)


and a blank screen.

----------

Looks like `regl-scatter2d` accepts `Int32Array` just fine. Could we make regl-splom do the same?

**Comment by dy** [comment]
Ok, now should be fixed )

**Comment by etpinard** [comment]
Sweet. This works:

```js
lotly.newPlot( gd,
			  [{
    "type": "splom",
    "dimensions": [{
      "values": new Int32Array([1, 2, 3]),
      "label": "A"
    }, {
      "values": new Int32Array([2, 5, 6]),
      "label": "B"
    }]
  }]);
```

gives
![image](https://user-images.githubusercontent.com/6675409/39495981-ac8515ee-4d6a-11e8-8cbe-158cdcd0445d.png)
